WMS #8021: Oracle AQ
oracle/microservices-datadriven pull request #269
Opened 2021-12-10 16:37 UTC by matayal

2021-12-10 17:14 UTC, paulparkinson requested changes
Made some comments inline. I have not reviewed the actual src detail yet just the basics re structure, etc..  In addition...
- I would rename the root dir from "oracleAQ" to the name of the app such as "cloudbank" or whatever it is to follow the convention of "Grabdish"
- It would be good to make the db etc. infra setup use the common core that @RichardExley has been working on so let's get him to review that aspect as well.
- Also, need to add copyright at the top of all files
Thanks.

2021-12-10 17:14 UTC, paulparkinson commented on oracleAQ/java/.gitignore
> +HELP.md
please remove this file

2021-12-10 17:14 UTC, paulparkinson commented on oracleAQ/java/.mvn/wrapper/MavenWrapperDownloader.java
> +/*
please remove this .mvn dir

2021-12-10 17:14 UTC, paulparkinson commented on oracleAQ/java/Dockerfile
> +mvn clean install
for Java builds we've been building and then packaging in dockerfile. this prevents building every time the service is deployed and also allows us to change the JDK image to jre-slim. see inventory-helidon etc. for examples

2021-12-10 17:14 UTC, paulparkinson commented on oracleAQ/java/src/main/java/com/aq/java/OracleAQController.java
> +package com.aq.java;
naming the directory "java" makes things confusing/ambiguous with the "main/java" src location. please rename it to "aq-java" or some such

2022-01-17 16:33 UTC, matayal commented
refactoring the location of code.

2022-01-17 16:33 UTC, closed without merging