Add a Updating the TLS certificate section
oracle/microservices-datadriven pull request #737
Opened 2023-08-09 14:14 UTC by gotsysdba

2023-08-09 17:09 UTC, markxnelson approved these changes
please get review from @rhondaday too

2023-08-23 07:57 UTC, gotsysdba commented
@rhondaday, can you give this change a once-over and approve if good?

2023-08-31 14:18 UTC, rhondaday requested changes

2023-08-31 14:18 UTC, rhondaday commented on docs-source/mbaas/content/setup/_index.md
> +The Oracle Backend for Parse Platform is deployed with a sample "Self-Signed" certificate for TLS.  This results in an "Accept Risk" message when accessing the Parse Dashboard and the sample TLS cert
Change "Self-Signed" to self-signed (no quote; no caps)

2023-08-31 14:18 UTC, rhondaday commented on docs-source/mbaas/content/setup/_index.md
> +1. Ensure your DNS entry points to the IP Address specified in the `parse_dahsboard_uri` output.
Change Address to address

2023-10-17 12:56 UTC, markxnelson submitted a review, later dismissed
LGTM

2023-10-17 15:00 UTC, rhondaday commented on docs-source/mbaas/content/setup/_index.md
> +The Oracle Backend for Parse Platform is deployed with a sample self-signed certificate for TLS.  This results in an "Accept Risk" message when accessing the Parse Dashboard and the sample TLS certif
In the first sentence, change "TLS" to "Transport Layer Security (TLS)".

It looks like there may be an extra space between sentences. There should only be one space between sentences.

2023-10-17 15:03 UTC, rhondaday commented on docs-source/mbaas/content/setup/_index.md
> +1. Ensure your DNS entry points to the IP address specified in the `parse_dashboard_uri` output.
Change to:

1. Ensure that your Domain Name System (DNS) entry ...

2023-10-17 15:04 UTC, rhondaday reviewed
Just a couple of comments.

2023-10-18 17:47 UTC, rhondaday approved these changes
Looks good.

2023-10-19 08:11 UTC, merged